import { SEVERITY_ORDER } from './constants.js'

/** Builds a markdown vulnerability report from a scan row. */
export function buildMarkdownReport(scan) {
  const findings = [...(scan.findings || [])].sort(
    (a, b) => SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity)
  )
  const counts = SEVERITY_ORDER
    .map(sev => [sev, findings.filter(f => f.severity === sev).length])
    .filter(([, n]) => n > 0)

  const lines = [
    `# VulnScan Report — ${scan.input_label || 'scan'}`,
    '',
    `- **Date:** ${new Date(scan.created_at).toLocaleString()}`,
    `- **Language:** ${scan.language || 'auto-detected'}`,
    `- **Findings:** ${findings.length}${counts.length ? ` (${counts.map(([s, n]) => `${n} ${s}`).join(', ')})` : ''}`,
    '',
  ]

  if (findings.length === 0) {
    lines.push('No vulnerabilities found — code passed all checks.')
  }

  for (const f of findings) {
    lines.push(`## [${f.severity}] ${f.name} (${f.owasp_id || 'n/a'})`, '')
    if (f.affected_lines?.length) lines.push(`**Lines:** ${f.affected_lines.join(', ')}`, '')
    if (f.description) lines.push(f.description, '')
    if (f.fix_recommendation) lines.push('**Fix:**', '', f.fix_recommendation, '')
  }

  lines.push('---', '_Generated by VulnScan — static analysis, not a substitute for review._')
  return lines.join('\n')
}
